### ISSUE TITLE
I just got this going under WSL2 on Windows 11

### ISSUE THREAD

**Issue by requaos** [dancrossnyc/r9#3]
<img width="339" alt="image" src="https://user-images.githubusercontent.com/14243154/175754735-768ad863-d5c3-4693-a3f9-7759f7a044d2.png">
I hope you don't mind some bare basic additions to the readme to cover installing llvm to get access to llvm-objcopy and explicitly installing the qemu-kvm package.

**Comment by dancrossnyc** [comment]
Can't say that I mind that, no.
